server:
  port: 7073
spring:
  application:
    name: wchat-api

management:
  endpoints:
    web:
      exposure:
        include: "*"

dubbo:
  registry:
    address : zookeeper://39.104.99.211:2181?backup=39.104.99.211:2182,39.104.99.211:2183
    client: curator
    timeout: 5000
  application:
    id: wchat-api
    name: wchat-api
    qos-enable: false
    qos-port: 2233

exception:
    handler:
      enable: true

aliyun:
    msg:
      enable: true
      accessKeyId: LTAItZnXWtTjngQK
      accessKeySecret: LeWr9pEHqUo69eG4qv3ksHcTUWP48C
    oss:
      enable: true
      accessKeyId: LTAItZnXWtTjngQK
      accessKeySecret: LeWr9pEHqUo69eG4qv3ksHcTUWP48C
      endpoint: http://oss-cn-beijing.aliyuncs.com
      bucketName: gm-file
      hostPrefix: https://f.guominpt.com
#  consumer:
#    filter: cn.likepeng.tx.dubbo.filter.TransactionFilter
#    loadbalance: cn.likepeng.tx.dubbo.balance.RandomLoadBalanceProxy

#tm.manager.url: http://localhost:8899/tx/manager/
