spring:
  application:
    name: register-one
  security:
    user:
      name: root
      password: 123

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://root:123@39.104.99.211:9092/eureka/