server:
  port: 8081
spring:
  application:
    name: admin-service-provider

management:
  endpoints:
    web:
      exposure:
        include: "*"

dubbo:
  registry:
    address : zookeeper://39.104.99.211:2181?backup=39.104.99.211:2182,39.104.99.211:2183
    client: curator
    subscribe: false
  application:
    id: admin-service-provider,
    name: admin-service-provider
    qos-enable: false
    qos-port: 2233
